a={1,2,3,1,2,3,4,(7,2,9)}
# print(type(a))
# print(a)
# a={}
# print(type(a))   #prints empty dictionary
b=set()
# print(type(b))   #prints empty set
b.add(12)
b.add(90)
b.add(6)
b.add((7,2,3))
# print(b)
# print(len(b))
# print(b.remove(4))
# # print(b.remove(40))
# b.add(3)
# b.add(4)
# print(b.pop())
# print(b)
# print(b.clear())
print(a.intersection(b),"\n",a.union(b),"\n",b.intersection(a),"\n",b.union(a),"\n",b.intersection({12,90,1,23}))
num1=input("enter number:")
num2=input("enter number:")
num3=input("enter number:")
num4=int(input("enter number:"))
num5=int(input("enter number:"))
num6=int(input("enter number:"))
print(num1,num2,num3,num4,num5,num6)
print(num1+num2+num3)
print(num4*num5+num6)